language: node
node_js:
  - 7
sudo: required
services:
  - docker

before_install:
  - docker build -t vkaukeano/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vkaukeano/docker-react npm run test -- --coverage
