language: node
node_js:
  - lts/*
sudo: required
services:
  - docker

before_install:
  - docker build -t vkaukeano/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vkaukeano/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: Docker-env
  bucket_name: arn:aws:s3:::elasticbeanstalk-us-east-1-602578598081
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
